site_name: TOS docs
nav:
  - Home: index.md
  - FP: just a page.md
theme:
  logo: assets/icon.png
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: lime
  font:
    text: JetBrains Mono

