site_name: TOS docs
nav:
  - Home: index.md
  - Business reqs: business requirements.md
  - Arch: architectural solutions.md
theme:
  logo: assets/icon.png
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: lime
  font:
    text: JetBrains Mono

